---
- name: Create CRITs user
  user: name=crits

- name: Add Apache user (www-data) to CRITs group
  command: usermod -a -G crits www-data

- name: Create CRITs directory structure
  command: mkdir -p /data/crits creates=/data/crits

- name: Move (copy for test-sake) crits code
  command: cp -pfr /vagrant/crits /data/ creates=/data/crits/logs

- name: Change group permissions of logs
  command: chgrp -R crits /data/crits/logs

- name: Create log file
  command: touch /data/crits/logs/crits.log creates=/data/crits/logs/crits.log

- name: Set permissions on log file
  command: chmod 664 /data/crits/logs/crits.log

- name: Create database config file
  template: src=database.py dest=/data/crits/crits/config/database.py

- name: Create default MongoDB collection
  command: python manage.py create_default_collections chdir=/data/crits

- name: Add the first user
  command: python manage.py users -a -A -u admin -e foo@bar.com > /vagrant/admin_password.txt chdir=/data/crits

- debug: msg=ADMIN TMP PASSWORD IS IN admin_password.txt

- name: Set allowed hosts
  command: python manage.py setconfig allowed_hosts "192.168.13.40" chdir=/data/crits

# DEVELOPMENT / TEST:

- name: Removing Apache2 to prevent port in use
  command: apt-get -y purge apache2*

- name: Move in server run script
  template: src=runserver.sh dest=/data/crits/runserver.sh

- name: Change script permissions
  command: chmod +x runserver.sh chdir=/data/crits

- name: Start development server (NO SSL)
  command: ./runserver.sh chdir=/data/crits

- name: Add Cronjob for mapreduces
  cron: name="crits mapreduces" minute="0" job="cd /data/crits/ && /usr/bin/python manage.py mapreduces"

- name: Add Cronjob for notifications
  cron: name="crits notifications" minute="0" job="cd /data/crits/ && /usr/bin/python manage.py generate_notifications"